ALTER TABLE customer RENAME COLUMN "Customer ID" TO customer_id;
ALTER TABLE customer RENAME COLUMN "Age" TO age;
ALTER TABLE customer RENAME COLUMN "Gender" TO gender;
ALTER TABLE customer RENAME COLUMN "Item Purchased" TO item_purchased;
ALTER TABLE customer RENAME COLUMN "Category" TO category;
ALTER TABLE customer RENAME COLUMN "purchase_amount_usd" TO purchase_amount;
ALTER TABLE customer RENAME COLUMN "Location" TO location;
ALTER TABLE customer RENAME COLUMN "Size" TO size;
ALTER TABLE customer RENAME COLUMN "Color" TO color;
ALTER TABLE customer RENAME COLUMN "Season" TO season;
ALTER TABLE customer RENAME COLUMN "Review Rating" TO review_rating;
ALTER TABLE customer RENAME COLUMN "Subscription Status" TO subscription_status;
ALTER TABLE customer RENAME COLUMN "Shipping Type" TO shipping_type;
ALTER TABLE customer RENAME COLUMN "Discount Applied" TO discount_applied;
ALTER TABLE customer RENAME COLUMN "Promo Code Used" TO promo_code_used;
ALTER TABLE customer RENAME COLUMN "Previous Purchases" TO previous_purchases;
ALTER TABLE customer RENAME COLUMN "Payment Method" TO payment_method;
ALTER TABLE customer RENAME COLUMN "Frequency of Purchases" TO frequency_of_purchases;

select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customers?

SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. What are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied= 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY COUNT(*) DESC;


--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;

